[package]
name = "unsaac-docs"
version = "0.2.1"
entrypoint = "lib.typ"
authors = ["Daniel A. Sallo <ccusdanielalegriasallo7@gmail.com>"]
license = "MIT"
description = "Coleccion de plantillas para trabajos de la UNSAAC."
repository = "https://github.com/daniel-alegria3/typst-unsaac"
categories = ["thesis", "report", "presentation"]
keywords = ["universidad", "unsaac", "tesis", "trabajo", "reporte", "presentation"]
exclude = ["example.*"]

[template]
path = "templates"
entrypoint = "tesis.typ"
thumbnail = "thumbnail.png"
